apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: joey.k8s.local
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://joey-kops-bkt/joey.k8s.local
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m 
    etcdMembers:
    - instanceGroup: master-joey
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-joey
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.19.7
  masterPublicName: api.joey.k8s.local
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: ap-southeast-2a
    type: Public
    zone: ap-southeast-2a
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: joey.k8s.local
  name: master-joey
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: t2.micro
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: master-joey
  role: Master
  subnets:
  - ap-southeast-2a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: joey.k8s.local
  name: nodes-joey
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/joey.k8s.local: ""
  machineType: t2.micro
  maxSize: 10
  minSize: 8
  mixedInstancesPolicy:
    instances:
    - t2.micro
    onDemandAboveBase: 0
    onDemandBase: 1
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-joey
  role: Node
  subnets:
  - ap-southeast-2a

---