apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: {{.clusterName}}
spec:
  api:
    loadBalancer:
      class: Classic
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: {{.kopsStateStore}}/{{.clusterName}}
  containerRuntime: docker
  etcdClusters:
  - cpuRequest: 200m 
    etcdMembers:
    - instanceGroup: {{.igMasterName}}
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: {{.igMasterName}}
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: {{.kubernetesVersion}}
  masterPublicName: api.{{.clusterName}}
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: {{.awsRegion}}
    type: Public
    zone: {{.awsRegion}}
  topology:
    dns:
      type: Public
    masters: public
    nodes: public

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: {{.clusterName}}
  name: {{.igMasterName}}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  machineType: {{.masterInstanceType}}
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: {{.igMasterName}}
  role: Master
  subnets:
  - {{.awsRegion}}

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{.clusterName}}
  name: {{.igNodesName}}
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
    k8s.io/cluster-autoscaler/{{.clusterName}}: ""
  machineType: {{.nodeInstanceType}}
  maxSize: 10
  minSize: 5
  nodeLabels:
    kops.k8s.io/instancegroup: {{.igNodesName}}
  role: Node
  subnets:
  - {{.awsRegion}}

---